//! flow-rs · registry —— 编译期节点注册表（Ch2.4）。
//!
//! 引擎要按 TOML 里的**类型名字符串**（如 `"Doubler"`）把节点造出来，就需要一张
//! 「名字 → 构造器」的表。难点在于：节点定义**分散在各处**（内置节点在 flow-rs、
//! 业务节点在下游 crate），却要在**运行前**汇成一张全局表——这正是「编译期分布式
//! 注册」。
//!
//! 原版 MegFlow 为此自建了一套：`#[flow_rs::ln]` 属性宏 + `lazy_static` 全局表 +
//! 首次访问时的运行时注册。我们**换成成熟公共 crate [`inventory`]**：它用链接期的
//! section 收集机制，把各处 `inventory::submit!` 的条目在 **link 阶段**就拼进一张表，
//! 运行时 `inventory::iter` 直接枚举——少一套要自己维护的注册机制，也没有首次访问的
//! 运行时开销。
//!
//! 三个部件：
//! - [`NodeRegistration`]：一条注册条目 = `{ 名字, 构造器 }`。用 [`inventory::collect`]
//!   在**本 crate**声明「要收集的就是这种条目」。
//! - [`BuildFromPorts`]：节点的**位置接线构造器** trait，由 `#[derive(BuildFromPorts)]`
//!   生成——把一串输入/输出端口按字段顺序填进结构体。
//! - `node_register!("Name", Type)`（在 flow-derive）：在**任意 crate**用
//!   `flow_rs::inventory::submit!` 提交一条 `NodeRegistration`，`ctor` 指向
//!   `<Type as BuildFromPorts>::build`。
//!
//! Compile-time distributed node registry, backed by the `inventory` crate
//! (replaces the original's hand-rolled `#[flow_rs::ln]` + lazy_static table).

use crate::channel::{Receiver, Sender};
use crate::error::Result;
use crate::node::Actor;

/// 节点构造器：吃**节点参数表** + 一串输入端口 + 一串输出端口，产出类型擦除的
/// `Box<dyn Actor>`（失败 → `Err`）。
///
/// 相对 Ch2.4 的签名，Ch3.2 加了两样：
/// - `&Args`：节点的自有参数（`op="+"`）从这里反序列化进字段——「配置驱动」的落点。
/// - `-> Result`：参数缺失/类型错、乃至端口对不上，都在 `build()` 当场报错。
///
/// 端口仍按 **位置**（`Vec` 顺序）填字段，但顺序不再随意——它与本条目的
/// [`NodeRegistration::inputs`]/[`outputs`] 端口名表**同序**，Graph Builder 正是靠这层
/// 对应把「TOML 里按名接的 channel」排成「构造器要的按位置 Vec」。用裸函数指针（而非
/// 闭包）是为了让条目能在 `static` 上下文里 const 构造，满足 `inventory::submit!`。
/// A node constructor: args + positional ports in, type-erased actor (or error) out.
pub type NodeCtor = fn(&crate::config::Args, Vec<Receiver>, Vec<Sender>) -> Result<Box<dyn Actor>>;

/// 注册表里的一条条目：类型名 + 端口名表 + 构造器。
/// One registry entry: type name, port-name tables, and constructor.
pub struct NodeRegistration {
    /// 节点类型名——TOML 里按它引用节点（注册表 key）。
    pub name: &'static str,
    /// 输入端口名，**按构造器填充顺序**（= 结构体里 `Receiver` 字段的声明顺序）。
    /// Graph Builder 用它把命名 channel 排成 `ctor` 要的位置 `Vec`。
    pub inputs: &'static [&'static str],
    /// 输出端口名，同上（= `Sender` 字段的声明顺序）。
    pub outputs: &'static [&'static str],
    /// 该类型的构造器（`<T as BuildFromPorts>::build`）。
    pub ctor: NodeCtor,
}

// 声明「本 crate 收集 `NodeRegistration` 条目」。`collect!` 必须与被收集类型同 crate，
// 且在 item 位置（模块级）。各处 `submit!` 的条目在 link 期汇入这张表。
inventory::collect!(NodeRegistration);

/// 「从端口构造节点」的 trait，由 `#[derive(BuildFromPorts)]` 生成实现。
///
/// 生成的 `build` 把 `ins`/`outs` 按**字段声明顺序**填入结构体：类型含 `Receiver` 的
/// 字段取一个输入端口、含 `Sender` 的取一个输出端口（包成 `Some`）、`input_closed`
/// 置 `false`、其余字段（节点自有参数）用 [`crate::config::arg`] 从 `args` 按字段名
/// 反序列化。`INPUTS`/`OUTPUTS` 是同一次字段遍历里收集的端口名表（与填充顺序同序），
/// 交给 Graph Builder 做「名字 → 位置」的桥。
///
/// 不设 `where Self: Sized`——我们只以 `<ConcreteType as BuildFromPorts>::build` 取函数
/// 指针 / `::INPUTS` 取常量，从不需要 `dyn BuildFromPorts`。
/// Constructs a node from args + ports; impl generated by `#[derive(BuildFromPorts)]`.
pub trait BuildFromPorts {
    /// 输入端口名，按 `build` 消费 `ins` 的顺序。/ input port names, in fill order.
    const INPUTS: &'static [&'static str];
    /// 输出端口名，按 `build` 消费 `outs` 的顺序。/ output port names, in fill order.
    const OUTPUTS: &'static [&'static str];

    /// 用 `args` 填自有参数、按顺序接好端口，返回擦除后的节点（失败 → `Err`）。
    /// Fill args, wire ports by order; return the type-erased node (or error).
    fn build(
        args: &crate::config::Args,
        ins: Vec<Receiver>,
        outs: Vec<Sender>,
    ) -> Result<Box<dyn Actor>>;
}

/// 枚举所有已注册节点（link 期汇总的全局表）。
/// Iterate over every registered node.
pub fn registrations() -> impl Iterator<Item = &'static NodeRegistration> {
    inventory::iter::<NodeRegistration>.into_iter()
}

/// 按类型名查一条注册。Part 3 的 Graph Builder 会用它把 TOML 里的类型名解析成构造器。
/// Look up one registration by type name.
pub fn find(name: &str) -> Option<&'static NodeRegistration> {
    registrations().find(|r| r.name == name)
}
