//! flow-rs · registry —— 编译期节点注册表（Ch2.4）。
//!
//! 引擎要按 TOML 里的**类型名字符串**（如 `"Doubler"`）把节点造出来，就需要一张
//! 「名字 → 构造器」的表。难点在于：节点定义**分散在各处**（内置节点在 flow-rs、
//! 业务节点在下游 crate），却要在**运行前**汇成一张全局表——这正是「编译期分布式
//! 注册」。
//!
//! 原版 MegFlow 为此自建了一套：`#[flow_rs::ln]` 属性宏 + `lazy_static` 全局表 +
//! 首次访问时的运行时注册。我们**换成成熟公共 crate [`inventory`]**：它用链接期的
//! section 收集机制，把各处 `inventory::submit!` 的条目在 **link 阶段**就拼进一张表，
//! 运行时 `inventory::iter` 直接枚举——少一套要自己维护的注册机制，也没有首次访问的
//! 运行时开销。
//!
//! 三个部件：
//! - [`NodeRegistration`]：一条注册条目 = `{ 名字, 构造器 }`。用 [`inventory::collect`]
//!   在**本 crate**声明「要收集的就是这种条目」。
//! - [`BuildFromPorts`]：节点的**位置接线构造器** trait，由 `#[derive(BuildFromPorts)]`
//!   生成——把一串输入/输出端口按字段顺序填进结构体。
//! - `node_register!("Name", Type)`（在 flow-derive）：在**任意 crate**用
//!   `flow_rs::inventory::submit!` 提交一条 `NodeRegistration`，`ctor` 指向
//!   `<Type as BuildFromPorts>::build`。
//!
//! Compile-time distributed node registry, backed by the `inventory` crate
//! (replaces the original's hand-rolled `#[flow_rs::ln]` + lazy_static table).

use crate::channel::{Receiver, Sender};
use crate::node::Actor;

/// 节点构造器：吃一串输入端口 + 一串输出端口，产出一个类型擦除的 `Box<dyn Actor>`。
///
/// 端口用 **位置**（`Vec` 顺序）对应字段——本章足够；Part 3 的 Graph Builder 会改用
/// TOML 里的命名 `PortInfo` 接线。用裸函数指针（而非闭包）是为了让条目能在 `static`
/// 上下文里 const 构造，满足 `inventory::submit!` 的要求。
/// A node constructor: positional ports in, type-erased actor out.
pub type NodeCtor = fn(Vec<Receiver>, Vec<Sender>) -> Box<dyn Actor>;

/// 注册表里的一条条目：类型名 + 构造器。
/// One registry entry: the node's type name and its constructor.
pub struct NodeRegistration {
    /// 节点类型名——TOML 里按它引用节点（注册表 key）。
    pub name: &'static str,
    /// 该类型的构造器（`<T as BuildFromPorts>::build`）。
    pub ctor: NodeCtor,
}

// 声明「本 crate 收集 `NodeRegistration` 条目」。`collect!` 必须与被收集类型同 crate，
// 且在 item 位置（模块级）。各处 `submit!` 的条目在 link 期汇入这张表。
inventory::collect!(NodeRegistration);

/// 「从端口构造节点」的 trait，由 `#[derive(BuildFromPorts)]` 生成实现。
///
/// 生成的 `build` 把 `ins`/`outs` 按**字段声明顺序**填入结构体：类型含 `Receiver` 的
/// 字段取一个输入端口、含 `Sender` 的取一个输出端口（包成 `Some`）、`input_closed`
/// 置 `false`、其余走 `Default::default()`。
///
/// 不设 `where Self: Sized`——我们只以 `<ConcreteType as BuildFromPorts>::build` 取函数
/// 指针，从不需要 `dyn BuildFromPorts`。
/// Constructs a node from its ports; impl generated by `#[derive(BuildFromPorts)]`.
pub trait BuildFromPorts {
    /// 按字段顺序接好端口，返回擦除后的节点。
    /// Wire ports by field order; return the type-erased node.
    fn build(ins: Vec<Receiver>, outs: Vec<Sender>) -> Box<dyn Actor>;
}

/// 枚举所有已注册节点（link 期汇总的全局表）。
/// Iterate over every registered node.
pub fn registrations() -> impl Iterator<Item = &'static NodeRegistration> {
    inventory::iter::<NodeRegistration>.into_iter()
}

/// 按类型名查一条注册。Part 3 的 Graph Builder 会用它把 TOML 里的类型名解析成构造器。
/// Look up one registration by type name.
pub fn find(name: &str) -> Option<&'static NodeRegistration> {
    registrations().find(|r| r.name == name)
}
